"""
Copyright © 2024 Axioma by SimCorp.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.

"""
import logging

from axiomapy.session import AxiomaSession
from axiomapy.utils import odata_params

_logger = logging.getLogger(__name__)
_logger.addHandler(logging.NullHandler())


class IAPPerformanceIntegrationAPI:
    """Access API methods of Investment Analytics Platform Performance Integration using an active Axioma Session

    """

    @staticmethod
    def post_iap_performance_integration(
            payload: dict,
            upload: bool = True,
            headers: dict = None,
            return_response: bool = False,
    ):
        """This method extracts the requested data from data mart, transform it and send it to the Invest App via the IAP integration Service API

        Args:
            payload: json payload for the request
            upload: Optional flag signal whether to upload IAP Performance or not
            headers: Optional headers, if any required (Correlation ID , Content-Encoding)
            return_response: If set to true, the response will be returned

        Returns:
            Success message if export request is successfully received
        """

        filter_string = f"upload={upload}"
        url = f"/iap-performance-integration?{filter_string}"
        _logger.info(f"Posting to {url}")
        response = AxiomaSession.current._post(
            url, json=payload, headers=headers, return_response=return_response
        )
        return response

    @staticmethod
    def get_iap_performance_integration_logs(
            request_id: str,
            filter_results: str = None,
            top: int = None,
            skip: int = None,
            orderby: str = None,
            return_response: bool = False,
    ):
        """This method returns the logs generated by an export request

        Args:
            request_id: the request id returned when the request is submitted
            filter_results:user can apply filter to the list
            top:returns top N number of elements
            skip:skips first N elements
            orderby:sorts in particular order
            return_response: If set to true, the response will be returned

        Returns:
            Logs related to the request
        """

        params = odata_params(filter_results, top, skip, orderby)
        url = f"/iap-performance-integration/{request_id}/logs"
        _logger.info(f"Get from {url}")
        response = AxiomaSession.current._get(
            url, params=params, return_response=return_response
        )
        return response

    @staticmethod
    def get_iap_performance_integration_status(
            request_id: str,
            return_response: bool = False,
    ):
        """This method returns the status of the export request

        Args:
            request_id: the request id returned when request is submitted
            return_response: If set to true, the response will be returned

        Returns:
            Status of the request
        """

        url = f"/iap-performance-integration/{request_id}/status"
        _logger.info(f"Get from {url}")
        response = AxiomaSession.current._get(
            url, return_response=return_response
        )
        return response