# Validates that restricted secrets are only used in actions and workflows maintained by the Release/Pipeline teams.
# i.e.
# secrets.CORE_<ANYTHING> can only be used in the following: 
#  - job steps calling actions defined in the Qontigo/devops-gh-actions repository
#  - jobs calling reusable workflows defined in the Qontigo/devops-gh-actions repository
#  - actions or workflows in any repo which are prefixed with 'core-' and maintained by the 
#    Release/Pipeline teams (typically sync'ed into a target repository from Qontigo/devops-gh-actions)
# 
# Any other (unrestricted) secrets can be used by any workflows or actions in any repo

name: Validate Restricted Secret Use
run-name: "${{ github.event_name == 'pull_request' && format('pull/{0} => {1} - {2}', github.event.pull_request.number, github.event.pull_request.base.ref, github.event.pull_request.title) || format('{0} {1} - {2}', github.ref_name, github.event_name, github.event_name == 'workflow_dispatch' && format('run by {0}', github.actor) || github.event.head_commit.message) }}"

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - '.github/**'
      - '!.github/**/core-*' 
    
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - '.github/**'
      - '!.github/**/core-*'

jobs:
  check_secret_usage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 1
        show-progress: false
        sparse-checkout: | 
          .github
          scripts
        sparse-checkout-cone-mode: false

    - name: Check CORE_ Secrets
      uses: Qontigo/devops-gh-actions/.github/actions/core-check-secret-usage@main
