# NOTE: This file is maintained in the Qontigo/devops-gh-actions repo (templates/core-pr-target-check.yml) and that copy will overwrite any changes made in any repo using the file
#       If changes are necessary to this file then you will need to raise a PR in that repo and perform appropriate testing with repos which use this file

# Checks that the target for a PR is correct based on the name of the source branch.
# e.g.
# feature/XXX PRs can be only be merged to master
# relfix/XXX PRs can only be merged to release/NNN branches
# prod can be merged into master or a release/NNN branch

name: PR Target Check
run-name: "${{ github.event_name == 'pull_request' && format('pull/{0} => {1} - {2}', github.event.pull_request.number, github.event.pull_request.base.ref, github.event.pull_request.title) || format('{0} {1} - {2}', github.ref_name, github.event_name, github.event_name == 'workflow_dispatch' && format('run by {0}', github.actor) || github.event.head_commit.message) }}"

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check_target:
    uses: Qontigo/devops-gh-actions/.github/workflows/core-pr-target-check.yml@main