name: Automatically Add Approver Individuals and Groups - master branch

on:
  workflow_dispatch:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ opened ]
          
jobs:
  add_reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Add Reviewers
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          github-token: ${{secrets.QONTIGO_GH_ACTION_PAT}}
          script: |
            github.rest.pulls.requestReviewers({
              pull_number: context.payload.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              team_reviewers: ['technologysolutions']
            })
